import {
  siApachekafka,
  siDocker,
  siDotnet,
  siElasticsearch,
  siExpress,
  siGo,
  siGooglecloud,
  siGrafana,
  siJavascript,
  siJest,
  siKubernetes,
  siMariadb,
  siMongodb,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siPostgresql,
  siReact,
  siRedis,
  siRedux,
  siSharp,
  siTypescript,
} from 'simple-icons'
import type { SimpleIcon } from 'simple-icons'

export const techLogos: Record<string, SimpleIcon | null> = {
  'React': siReact,
  'Next.js': siNextdotjs,
  'React Native': siReact,
  'Redux': siRedux,
  'JavaScript': siJavascript,
  'TypeScript': siTypescript,
  'Node.js': siNodedotjs,
  'NestJS': siNestjs,
  'Express': siExpress,
  'Go': siGo,
  '.NET': siDotnet,
  'C#': siSharp,
  'PostgreSQL': siPostgresql,
  'MongoDB': siMongodb,
  'MySQL': siMysql,
  'SQL Server': null,
  'MariaDB': siMariadb,
  'Redis': siRedis,
  'Kafka': siApachekafka,
  'Azure Service Bus': null,
  'AWS': null,
  'GCP': siGooglecloud,
  'Azure': null,
  'Docker': siDocker,
  'Kubernetes': siKubernetes,
  'Jest': siJest,
  'Elasticsearch': siElasticsearch,
  'Grafana': siGrafana,
}
